export const mn = {
  appTitle: 'SUNIA Админ',
  appDescription: 'SUNIA гар утасны аппын админ самбар',
  adminPanel: 'Админ самбар',
  management: 'Удирдлага',
  logout: 'Гарах',

  dashboard: 'Самбар',
  users: 'Хэрэглэгчид',
  workouts: 'Хөтөлбөр',
  exercises: 'Дасгал',
  sessions: 'Сесс',
  challenges: 'Челленж',
  products: 'Бүтээгдэхүүн',
  productCategories: 'Бүтээгдэхүүний ангилал',
  addProductCategory: 'Ангилал нэмэх',
  editProductCategory: 'Ангилал засах',
  newProductCategory: 'Шинэ ангилал',
  slug: 'Slug',
  slugHint: 'Жишээ: gear, accessory (апп шүүлтүүр)',
  iconHint: 'Material icon нэр (жишээ: fitness_center)',
  deleteProductCategory: 'Энэ ангилалыг устгах уу?',
  selectCategory: 'Ангилал сонгох',
  badges: 'Тэмдэгт',
  leaderboard: 'Лидерборд',
  duels: 'Тулаан',
  orders: 'Захиалга',
  settings: 'Тохиргоо',
  notifications: 'Push мэдэгдэл',
  qpay: 'QPay',
  qpayEnabled: 'QPay идэвхжүүлэх',
  qpayHint: 'Унтраавал хэрэглэгч апп дээр QPay-ээр төлж чадахгүй.',
  qpayClientId: 'QPay Login (Client ID)',
  qpayClientSecret: 'QPay Password (Secret)',
  qpayInvoiceCode: 'Invoice code',
  qpayReceiverCode: 'Receiver code',
  qpayBaseUrl: 'QPay API URL',
  qpayCallbackUrl: 'Callback URL',
  qpayConfigured: 'Merchant тохиргоо бэлэн',
  qpayNotConfigured: 'Merchant тохиргоо дутуу — demo QR ашиглагдана',
  save: 'Хадгалах',
  saved: 'Хадгаллаа',
  saving: 'Хадгалж байна...',
  saveFailed: 'Хадгалахад алдаа гарлаа',
  phone: 'Утас',
  address: 'Хаяг',
  payment: 'Төлбөр',

  signIn: 'Нэвтрэх',
  signingIn: 'Нэвтэрч байна...',
  signInDescription: 'SUNIA аппын админ самбарт нэвтэрнэ үү',
  email: 'Имэйл',
  google: 'Google',
  password: 'Нууц үг',
  loginFailed: 'Нэвтрэх амжилтгүй',

  totalUsers: 'Нийт хэрэглэгч',
  activeUsers: 'идэвхтэй',
  subscribers: 'Захиалагчид',
  publishedPrograms: 'Нийтэлсэн хөтөлбөр',
  publishedExercises: 'Нийтэлсэн дасгал',
  activeChallenges: 'Идэвхтэй челленж',
  inShop: 'Дэлгүүрт',
  totalSessions: 'Дасгалын сесс',
  totalReps: 'Нийт суниалт',
  recentUsers: 'Сүүлийн хэрэглэгчид',
  noUsersYet: 'Хэрэглэгч байхгүй',
  unknown: 'Тодорхойгүй',
  dayStreak: 'хоног',
  loadDashboardFailed: 'Самбар ачаалахад алдаа гарлаа',
  loading: 'Ачааллаж байна...',

  searchPlaceholder: 'Нэр эсвэл имэйлээр хайх...',
  search: 'Хайх',
  name: 'Нэр',
  streak: 'Дараалал',
  minutes: 'Минут',
  plus: 'Plus',
  subscriptionPlan: 'Төлөвлөгөө',
  subscriptionStart: 'Эхлэх',
  subscriptionEnd: 'Дуусах',
  subscriptionNone: 'Байхгүй',
  subscriptionMonthly: '1 сар',
  subscriptionQuarterly: '3 сар',
  subscriptionYearly: '1 жил',
  subscriptionGrantFailed: 'Гишүүнчлэл олгоход алдаа гарлаа',
  active: 'Идэвхтэй',
  inactive: 'Идэвхгүй',
  noUsersFound: 'Хэрэглэгч олдсонгүй',
  deleteUser: 'Энэ хэрэглэгчийг устгах уу?',
  days: 'хоног',
  min: 'мин',
  reps: 'суниалт',

  addWorkout: 'Хөтөлбөр нэмэх',
  editWorkout: 'Хөтөлбөр засах',
  newWorkout: 'Шинэ хөтөлбөр',
  title: 'Гарчиг',
  subtitle: 'Дэд гарчиг',
  level: 'Түвшин',
  tags: 'Шошго (таслалаар тусгаарлана)',
  type: 'Төрөл',
  durationMin: 'Үргэлжлэх хугацаа (мин)',
  duration: 'Хугацаа',
  publish: 'Нийтлэх',
  published: 'Нийтэлсэн',
  draft: 'Ноорог',
  status: 'Төлөв',
  actions: 'Үйлдэл',
  deleteWorkout: 'Энэ хөтөлбөрийг устгах уу?',
  update: 'Шинэчлэх',
  create: 'Үүсгэх',

  addExercise: 'Дасгал нэмэх',
  editExercise: 'Дасгал засах',
  newExercise: 'Шинэ дасгал',
  summary: 'Товч тайлбар',
  muscles: 'Булчин (таслалаар)',
  targetReps: 'Зорилтот давталт',
  videoUrl: 'Видео холбоос',
  imageUrl: 'Зургийн холбоос',
  exerciseProfileImage: 'Жагсаалтын зураг',
  exerciseProfileImageHint: 'Дасгалууд tab дээр харагдах жижиг зураг.',
  exerciseCoverImage: 'Cover зураг',
  exerciseCoverImageHint: 'Дасгалын дэлгэрэнгүй дээрх том hero зураг.',
  muscleImageUrl: 'Булчингийн зураг',
  uploadImage: 'Зураг оруулах',
  changeImage: 'Зураг солих',
  uploading: 'Байршуулж байна...',
  uploadFailed: 'Зураг байршуулахад алдаа гарлаа',
  uploadTooLarge: 'Зураг хэт том байна. Жижиг зураг сонгоно уу.',
  longDescription: 'Дэлгэрэнгүй тайлбар',
  primaryMuscles: 'Гол нөлөөлөх булчин',
  secondaryMuscles: 'Мөн ажиллах булчин',
  whyPoints: 'Яагаад хийх вэ? (мөр бүр нэг)',
  howPoints: 'Хэрхэн зөв хийх вэ? (мөр бүр нэг)',
  beginnerPlan: 'Эхлэх сет',
  standardPlan: 'Стандарт сет',
  advancedPlan: 'Хүчтэй сет',
  restNote: 'Амралтын тэмдэглэл',
  mistakes: 'Түгээмэл алдаа (мөр бүр нэг)',
  introSection: 'Дасгалын танилцуулга',
  deleteExercise: 'Энэ дасгалыг устгах уу?',
  noExercises: 'Дасгал байхгүй',

  addChallenge: 'Челленж нэмэх',
  editChallenge: 'Челленж засах',
  newChallenge: 'Шинэ челленж',
  description: 'Тайлбар',
  durationDays: 'Үргэлжлэх хоног',
  weeklyGoalDays: 'Долоо хоногийн зорилт (хоног)',
  timeLimit: 'Хугацааны хязгаар (сек)',
  deleteChallenge: 'Энэ челленжийг устгах уу?',
  challengeImage: 'Челленжийн зураг',
  challengeImageHint: 'Апп дээрх hero card болон дэлгэрэнгүй дээр харагдана.',
  rewardText: 'Шагналын текст',
  daysPerWeek: 'хоног/7 хоног',

  addProduct: 'Бүтээгдэхүүн нэмэх',
  editProduct: 'Бүтээгдэхүүн засах',
  newProduct: 'Шинэ бүтээгдэхүүн',
  product: 'Бүтээгдэхүүн',
  price: 'Үнэ (₮)',
  stock: 'Нөөц',
  category: 'Ангилал',
  rating: 'Үнэлгээ',
  reviews: 'Сэтгэгдэл',
  deleteProduct: 'Энэ бүтээгдэхүүнийг устгах уу?',
  productImages: 'Бүтээгдэхүүний зураг',
  addImage: 'Зураг нэмэх',
  removeImage: 'Зураг устгах',
  coverImage: 'Үндсэн',
  coverImageHint: 'Эхний зураг нь үндсэн зураг болно. Олон зураг байршуулж болно.',

  addBadge: 'Тэмдэгт нэмэх',
  editBadge: 'Тэмдэгт засах',
  newBadge: 'Шинэ тэмдэгт',
  key: 'Түлхүүр',
  icon: 'Дүрс',
  badgeImage: 'Тэмдэгтийн зураг',
  badgeImageHint: 'Хэрэглэгчийн профайл дээр харагдана.',
  deleteBadge: 'Энэ тэмдэгтийг устгах уу?',

  user: 'Хэрэглэгч',
  score: 'Оноо',
  completedAt: 'Дууссан',
  deleteSession: 'Энэ сессийг устгах уу?',
  noSessions: 'Сесс байхгүй',
  noLeaderboard: 'Лидерборд хоосон',
  daily: 'Өдөр тутмын',
  weekly: '7 хоног',
  allTime: 'Бүх цаг',
  opponent: 'Өрсөлдөгч',
  noDuels: 'Тулаан байхгүй',
  noOrders: 'Захиалга байхгүй',
  total: 'Нийт',
  items: 'Бараа',

  authRequired: 'Нэвтрэх шаардлагатай',
  requestFailed: 'Хүсэлт амжилтгүй',
  invalidCredentials: 'Буруу нэвтрэх мэдээлэл',
};

export const workoutTypeLabels: Record<string, string> = {
  stretching: 'Суниалт',
  core: 'Кор',
  recovery: 'Сэргэлт',
  push_up: 'Push-up',
};

export const challengeKindLabels: Record<string, string> = {
  daily: 'Өдөр тутмын',
  weekly: '7 хоног',
  friends: 'Найзууд',
  duel: 'Шууд тулаан',
};

export function translateApiError(message: string): string {
  if (message === 'Authentication required') return mn.authRequired;
  if (message === 'Invalid credentials') return mn.invalidCredentials;
  if (message === 'Cloudinary is not configured') return 'Cloudinary тохиргоо хийгээгүй байна';
  if (message.startsWith('Request failed')) return mn.requestFailed;
  if (message.startsWith('Upload failed')) return mn.uploadFailed;
  if (message === 'Payload too large' || message.includes('too large')) return mn.uploadTooLarge;
  return message;
}
